### PR TITLE
Allow Mojave

### PR DESCRIPTION
**Pull request by pje**
A group of mischievous gnomes broke into the Kickstarter office last night and upgraded my work laptop to Mojave! 

Normally of course I would never upgrade without waiting for Official IT Approval, but now that it's done I can confirm that Mojave works out of the box! 

Let's allow Mojave in case any other folks run into the same gnomes I did.

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]
🆙

**Review by garrow — APPROVED** [review]
These gnomes have been everywhere. I had to fight them off with a stick, but unfortunately failed, and have been running Mojave ever since.

**Comment by willmanduffy** [comment]
[extremely cyndi lauper voice]

🎵  gnomes just wanna have fun 🎵

**Pull request merged**
