### PR TITLE
Support Fish Shell

### PR DESCRIPTION
**Pull request by rapoulson**
_What_
Creates a `ksr.fish` instead of a `ksr.rc` for folks using the fish shell.

_Why_
14% of Kickstarter engineers are :fish: :turntbull:

cc @ktheory @talaris

### CODE REVIEW

**Comment by ktheory** [comment]
@rapoulson Please rewrite my "wip" commit for a clean history. :smile:

**Comment by ktheory** [comment]
:wave: @jamtur01 for a sanity check.

This provisions a ~/.config/fish/ksr.fish file with bits that kickstarter relies on; namely having `/usr/local/bin` in your `$PATH`, and initializing `rbenv`.

**Comment by jamtur01** [comment]
Seems reasonable. I'll patch if issues.

**Comment by tiegz** [comment]
Intrigued! Curious what the top benefits of Fish are, if anyone has time.

**Comment by jamtur01** [comment]
@tiegz Habit. :)

**Pull request merged**
